#----------------------
# Request info
#----------------------
ControlElem[] Controls
---
#----------------------
# Status types
#----------------------
int32 SUCCESS=1000
int32 FAIL=1001
#----------------------
# Response info
#----------------------
int32 Status
